apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gorana-joybird/grafana-operator.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
