apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: default
spec:
  instanceSelector:
    matchLabels:
      dashboards: my-grafana
  datasource:
    name: prometheus
    type: prometheus
    url: http://prometheus-server.grafana-operator.svc.cluster.local:80
    access: proxy
    jsonData:
      timeInterval: 5s
